---
title: "COVID-19 Excess Mortality"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: menu
    source_code: https://github.com/OxfordIHTM/excessmortalitydashboard
    theme: cerulean
---

```{r setup, include=FALSE}
if(!require(flexdashboard)) install.packages("flexdashboard")
if(!require(remotes)) install.packages("remotes")
if(!require(shiny)) install.packages("shiny")
if(!require(dplyr)) install.packages("dplyr")
if(!require(ggplot2)) install.packages("ggplot2")
if(!require(leaflet)) install.packages("leaflet")
if(!require(ggmap)) install.packages("ggmap")

if(!require(okapi)) remotes::install_github("rapidsurveys/okapi")

mapbox.leShine   <- "https://api.mapbox.com/styles/v1/ernestguevarra/cjdlr8pvl0xiv2sqvq1evk1pl/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.satellite <- "https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v10/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"
mapbox.iceCream  <- "https://api.mapbox.com/styles/v1/ernestguevarra/cj81sytkq8z5g2spicbkd4hmx/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoiZXJuZXN0Z3VldmFycmEiLCJhIjoiejRRLXlZdyJ9.sqS1zi0rDH5CIzvcn9SXSg"

Sys.setenv(GGMAP_GOOGLE_API_KEY = "AIzaSyAAWT7emntIW5zGmvuA213hwpH-eRo2y8I")

Sys.setenv(ONA_TOKEN = "a1ef6918bd05348140697b2379bada6939890a19")
ona_auth_token(token = Sys.getenv("ONA_TOKEN"))

formid <- reactive({
  okapi::ona_list_data() %>%
    dplyr::filter(id_string == "mortalitymetadata") %>%
    dplyr::select(id)
})

metadata <- reactive({
  okapi::ona_get_data(form_id = formid())
})
```

Sidebar {.sidebar}
================================================================================

```{r}
output$country_selection <- renderUI({
  selectInput(
    inputId = "select_country",
    label = "Select country",
    choices = metadata()$`location/country`,
    selected = NULL
  )  
})

uiOutput("country_selection")
```

Summary
================================================================================

Row
--------------------------------------------------------------------------------

### Map

```{r map}
country_locations <- reactive({
  xxx <- metadata()$`location/country`
  ggmap::geocode(location = xxx)
})

output$map <- renderLeaflet({
  leaflet(options = leafletOptions(minZoom = 2)) %>%
    addTiles(
      urlTemplate = mapbox.leShine,
      attribution = "Map by <a href='https://www.mapbox.com/'>Mapbox</a>"
    ) %>%
    addMarkers(lng = country_locations()$lon,
               lat = country_locations()$lat,
               popup = metadata()$`location/country`) %>%
    setView(lng = 0, lat = 25, zoom = 2)
})

leafletOutput("map", height = "350px")
```

Row
--------------------------------------------------------------------------------

### Submissions {.value-box}

```{r}
renderValueBox({
  valueBox(
    value = nrow(metadata()),
    caption = "Submissions",
    icon = "fa-database",
    color = "primary"
  )
})
```

### Countries {.value-box}

```{r}
renderValueBox({
  valueBox(
    value = length(metadata()$`location/country`),
    caption = "Countries",
    icon = "fa-globe",
    color = "primary"
  )
})
```

Row { .tabset .tabset-fade }
--------------------------------------------------------------------------------

### Organisation

```{r}
output$organisation_text <- renderText({
  paste("Characteristics of organisation in ", input$select_country,
        " responsible for mortality data.")
})

h4(textOutput("organisation_text"))

organisation_profile <- reactive({
  req(input$select_country)
  y <- metadata()
  x <- y[y$`location/country` == input$select_country, ]
  
  organisation_type    <- ifelse(x$`organisation/organisation_type` == "ngo",
                                 "Non-governmental organisation",
                            ifelse(x$`organisation/organisation_type` == "uno", 
                                   "United Nations (UN) organisation",
                              ifelse(x$`organisation/organisation_type` == "gov",
                                     "Government", "Other")))
  organisation_name    <- x$`organisation/organisation_name`
  organisation_address <- x$`organisation/organisation_contact_address`
  organisation_phone   <- x$`organisation/organisation_contact_phone`
  organisation_email   <- x$`organisation/organisation_contact_email`
  organisation_website <- x$`organisation/organisation_contact_website`
  
  tab <- data.frame(c("Organisation Type", "Organisation Name", "Organisation Address",
                      "Organisation Phone", "Organisation Email", "Organisation Website"),
                    c(organisation_type, organisation_name, organisation_address,
                      organisation_phone, organisation_email, organisation_website))
  names(tab) <- c("Feature", "Characteristics")
  
  tab
})

output$table1 <- DT::renderDT({ organisation_profile() })


DT::DTOutput("table1")
```

### Quality

```{r}
output$quality_text <- renderText({
  paste("Data quality processes in ", input$select_country,
        " for mortality data.")
})

h4(textOutput("quality_text"))

quality_profile <- reactive({
  req(input$select_country)
  y <- metadata()
  x <- y[y$`location/country` == input$select_country, ]
  
  data_quality_done    <- ifelse(x$`data_quality/data_quality_done` == 1, "Yes", "No")
  data_quality_process <- ifelse(data_quality_done == "No", NA,
                                 x$`data_quality/data_quality_process`)
  
  tab <- data.frame(c("Data quality check process applied to data?", 
                      "Description of data quality process"),
                    c(data_quality_done, data_quality_process))
  names(tab) <- c("Feature", "Characteristics")
  
  tab
})

output$table2 <- DT::renderDT({ quality_profile() })


DT::DTOutput("table2")
```

### Disaggregation

```{r}
output$disaggregation_text <- renderText({
  paste("Data disaggregation in ", input$select_country,
        " for mortality data.")
})

h4(textOutput("disaggregation_text"))

disaggregation_profile <- reactive({
  req(input$select_country)
  y <- metadata()
  x <- y[y$`location/country` == input$select_country, ]
  
  data_time_interval <- ifelse(x$`data_disaggregation/data_time_interval` == 1, 
                               "Yearly",
                          ifelse(x$`data_disaggregation/data_time_interval` == 2, 
                                 "Monthly",
                            ifelse(x$`data_disaggregation/data_time_interval` == 3, 
                                   "Weekly",
                              ifelse(x$`data_disaggregation/data_time_interval` == 4, 
                                     "No date/temporal information", "Don't know/not sure"))))

  data_gender        <- ifelse(x$`data_disaggregation/data_gender` == 1, "Yes", "No")
  data_age           <- ifelse(x$`data_disaggregation/data_age` == 1, "Yes", "No")
  data_place         <- ifelse(x$`data_disaggregation/data_place` == 1, "Yes", "No")
  data_location      <- ifelse(x$`data_disaggregation/data_location` == 1, 
                               "Level 1 administrative unit",
                          ifelse(x$`data_disaggregation/data_location` == 2,
                                 "Level 2 administrative unit",
                            ifelse(x$`data_disaggregation/data_location` == 3,
                                   "Level 3 administrative unit",
                              ifelse(x$`data_disaggregation/data_location` == 4,
                                     "By some subnational unit",
                                ifelse(x$`data_disaggregation/data_location` == 5,
                                       "No subnational location information", "Don't know/not sure")))))
  
  tab <- data.frame(c("Disaggregation by time", 
                      "Disaggregation by gender",
                      "Disaggregation by age",
                      "Disaggregation by place of death",
                      "Disaggregation by location of death"),
                    c(data_time_interval, data_gender, data_age, data_place, data_location))
  names(tab) <- c("Feature", "Characteristics")
  
  tab
})

output$table3 <- DT::renderDT({ disaggregation_profile() })


DT::DTOutput("table3")
```

Metadata
================================================================================

Row
--------------------------------------------------------------------------------

```{r}
output$metatable <- DT::renderDT({ metadata() })

DT::DTOutput("metatable")
```

